
export const PROJECT_LOAD = 'PROJECT_LOAD';
export const PROJECT_CLOSE = 'PROJECT_CLOSE';

export const CHANGELOG_LOAD = 'CHANGELOG_LOAD';
export const CHANGELOG_NOT_FOUND = 'CHANGELOG_NOT_FOUND';

export const EDITOR_EDITING = 'EDITOR_EDITING';
export const EDITOR_DONE_EDITING = 'EDITOR_DONE_EDITING';
